name: Build and Push Docker Image

on:
  push:
    tags: "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        packages: write
        contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-tags: true
        
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build --no-cache -t ghcr.io/${{ github.repository }}/nginx-image:${{ github.ref_name }} .
      
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/nginx-image:${{ github.ref_name }}

      - name: Pull Docker image with the correct tag
        run: |
          docker pull ghcr.io/${{ github.repository }}/nginx-image:${{ github.ref_name }}
        
      - name: Run Ansible Playbook for Deployment
        run: |
          ansible-playbook deploy-playbook.yml --extra-vars "new_version=${{ github.ref_name }}"
